### ISSUE TITLE
Error in configure_k8s/tasks/main.yml?

### ISSUE THREAD

**Issue by dazzag24** [rgee0/openfaas-DO#8]
Hi,
Firstly, thanks for the excellent blog post.  Really useful stuff and very well written.

Having followed the steps I find that after logging into my droplet and changing to the openfaas user I am unable to run the kubectl command.
```
>kubectl get pods
error: Error loading config file "/home/openfaas/.kube/config/admin.conf": open /home/openfaas/.kube/config/admin.conf: not a directory
```
If I examine the KUBECONFIG env var

```
set | grep KUBE
KUBECONFIG=/home/openfaas/.kube/config/admin.conf
```

is this correct?  should it be just 

`KUBECONFIG=/home/openfaas/.kube/config`

If so the offending line comes from line 9 in configure_k8s/tasks/main.yml

Thanks

**Comment by rgee0** [comment]
Thanks for the feedback @dazzag24 - very timely since the blog has featured in the monthly DOers mailing.  

I've just pushed and merged an amendment.
